name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  pull_request_review:
    types: [submitted]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: pre-commit
        run: |
          pip install -U pre-commit
          pre-commit install --install-hooks
          pre-commit run -a
  pytest:
    runs-on: ubuntu-latest
    needs: pre-commit
    container:
      image: nvcr.io/nvidia/tritonserver:22.01-pyt-python-py3
      options:
        --shm-size=1g
    steps:
      - uses: actions/checkout@v3
      - name: test bash
        env:
          TRITON_HOST: localhost
          TRITON_HTTP: 8000
          TRITON_GRPC: 8001
          TRITON_RETRIES: 2
          TRITON_CLIENT_TIMEOUT: 1
        run: |
          tritonserver --model-repo=$GITHUB_WORKSPACE/model_repository &
          pip install .[tests]
          sleep 3

          curl -v ${TRITON_HOST}:${TRITON_HTTP}/v2/health/ready
          pytest -s -n 4
